/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    "quickstart",
    "modules",
    "overview",
    "validation-dsl",
    "validation-error",
    "fail-with",
    "fieldpath",
    "rule",
    "validated",
    "effect",
    "policy",
    {
      "Value Module": [
          "value/field",
          "value/syntax",
      ]
    },
    {
      "Lens Module": [
        "lens/field-lens",
        "lens/syntax",
      ]
    },
    {
      "Interop": [
        "interop-circe",
        "interop-zio-blocks-schema",
      ]
    },
    "goals",
    "benchmarks",
    "contributing",
  ]
};

module.exports = sidebars;
