/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    "overview",
    {
      "Data Types": [
        "field",
        "fieldpath",
      ]
    },
    {
      "Type Classes": [
        "validation-result",
        "validation-effect",
        "validation-policy",
        "fail-with",
      ]
    }
    ,
    "validation-module",
    "goals",
    "contributing",
  ]
};

module.exports = sidebars;
